// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZD0QXjLBt2rXvagkXlkd6whHEE0Lqc0E',
    appId: '1:459534734920:web:f9345eeb9cf7146b792a7d',
    messagingSenderId: '459534734920',
    projectId: 'wagewise-c02f5',
    authDomain: 'wagewise-c02f5.firebaseapp.com',
    storageBucket: 'wagewise-c02f5.firebasestorage.app',
    measurementId: 'G-H7S8FFYYZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpGZDBLoCLe6MnHFqNlfLBzdcrzoLZQY',
    appId: '1:459534734920:android:e4d44bc145aecb74792a7d',
    messagingSenderId: '459534734920',
    projectId: 'wagewise-c02f5',
    storageBucket: 'wagewise-c02f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7i1x9z4UO5DWFzhE2D_MtFQYRWb189UY',
    appId: '1:459534734920:ios:18486a793fc9b70c792a7d',
    messagingSenderId: '459534734920',
    projectId: 'wagewise-c02f5',
    storageBucket: 'wagewise-c02f5.firebasestorage.app',
    iosBundleId: 'com.example.wagewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7i1x9z4UO5DWFzhE2D_MtFQYRWb189UY',
    appId: '1:459534734920:ios:18486a793fc9b70c792a7d',
    messagingSenderId: '459534734920',
    projectId: 'wagewise-c02f5',
    storageBucket: 'wagewise-c02f5.firebasestorage.app',
    iosBundleId: 'com.example.wagewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZD0QXjLBt2rXvagkXlkd6whHEE0Lqc0E',
    appId: '1:459534734920:web:373653c291cd4c4a792a7d',
    messagingSenderId: '459534734920',
    projectId: 'wagewise-c02f5',
    authDomain: 'wagewise-c02f5.firebaseapp.com',
    storageBucket: 'wagewise-c02f5.firebasestorage.app',
    measurementId: 'G-20QPG528K3',
  );
}
